name: Gradle tests

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.1.0
      - name: Set up JDK 14
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 14
      - name: Run tests with Gradle
        run: ./gradlew jvmTest
